$(document).ready(function(){
    $('.foodslider').slick({
        autoplay:true,
        slidesToShow:3,
        slidesToScroll:1,
        prevArrow:".prev-btn",
        nextArrow:".next-btn",

        responsive:[
            {
                breakpoint:992,
                settings:{
                    slidesToShow:2
                }
            },
            {
                breakpoint:768,
                settings:{
                    slidesToShow:1
                }
            }
        ]
    });
    $('.nav-triger').click(function(){
        $('.sit-contant-wreper').toggleClass('scaled');
    })
});